"use client";

import { useEffect, useRef, useState } from "react";
import CloseButton from "@/components/CloseButton";
import SourcePill from "@/components/SourcePill";

export default function PodcastPage() {
  const [podcastName, setPodcastName] = useState("");
  const [bannerUrl, setBannerUrl] = useState("");
  const [thumbnailUrl, setThumbnailUrl] = useState("");
  const [sourceLink, setSourceLink] = useState("");
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [speed, setSpeed] = useState(1);
  const [loaded, setLoaded] = useState(false);
  const [dominantColor, setDominantColor] = useState("rgba(88, 28, 135, 0.8)");

  const audioRef = useRef<HTMLAudioElement | null>(null);
  const seekBarRef = useRef<HTMLDivElement>(null);
  const speeds = [1, 1.5, 2, 4];

  useEffect(() => {
    fetch("/api/podcast")
      .then((r) => r.json())
      .then((data) => {
        if (data.error) return;
        setPodcastName(data.podcast_name);
        setBannerUrl(data.podcast_banner_url);
        setThumbnailUrl(data.podcast_thumbnail_url || "");
        setSourceLink(data.topic_source);
        audioRef.current = new Audio(data.podcast_audio_url);
        audioRef.current.preload = "metadata";
        audioRef.current.addEventListener("loadedmetadata", () => setDuration(audioRef.current!.duration));
        audioRef.current.addEventListener("timeupdate", () => setCurrentTime(audioRef.current!.currentTime));
        audioRef.current.addEventListener("play", () => setIsPlaying(true));
        audioRef.current.addEventListener("pause", () => setIsPlaying(false));
        audioRef.current.addEventListener("ended", () => setIsPlaying(false));
        setLoaded(true);

        // Get dominant color from banner
        if (data.podcast_banner_url) {
          fetch(`/api/dominant-color?imageUrl=${encodeURIComponent(data.podcast_banner_url)}`)
            .then((r) => r.json())
            .then((c) => setDominantColor(c.color))
            .catch(() => {});
        }
      })
      .catch(console.error);

    return () => { if (audioRef.current) { audioRef.current.pause(); audioRef.current.src = ""; } };
  }, []);

  const togglePlay = () => {
    if (!audioRef.current) return;
    if (audioRef.current.paused) audioRef.current.play(); else audioRef.current.pause();
  };

  const cycleSpeed = () => {
    const next = speeds[(speeds.indexOf(speed) + 1) % speeds.length];
    setSpeed(next);
    if (audioRef.current) audioRef.current.playbackRate = next;
  };

  const skip = (sec: number) => {
    if (!audioRef.current) return;
    audioRef.current.currentTime = Math.max(0, Math.min(duration, audioRef.current.currentTime + sec));
  };

  const seekTo = (e: React.MouseEvent<HTMLDivElement>) => {
    if (!seekBarRef.current || !audioRef.current) return;
    const rect = seekBarRef.current.getBoundingClientRect();
    audioRef.current.currentTime = (Math.max(0, Math.min(e.clientX - rect.left, rect.width)) / rect.width) * duration;
  };

  const formatTime = (sec: number) => {
    sec = Math.max(0, Math.floor(sec));
    return `-${Math.floor(sec / 60)}:${(sec % 60).toString().padStart(2, "0")}`;
  };

  const percent = duration > 0 ? (currentTime / duration) * 100 : 0;

  return (
    <section className="relative h-screen w-screen overflow-hidden">
      <CloseButton />

      {/* Gradient background */}
      <div className="absolute inset-0 transition-colors duration-1000" style={{ background: `linear-gradient(160deg, ${dominantColor}, #0a0a0a)` }} />

      {/* Banner blur */}
      {bannerUrl && (
        <div
          className="absolute inset-0 bg-cover bg-center transition-opacity duration-1000 opacity-20"
          style={{ backgroundImage: `url(${bannerUrl})`, filter: "blur(60px) brightness(0.4)" }}
        />
      )}

      {/* Thumbnail */}
      <div className="absolute top-[10%] left-1/2 -translate-x-1/2 z-10">
        {(thumbnailUrl || bannerUrl) && (
          <div
            className="w-[240px] h-[240px] rounded-[40px] bg-cover bg-center shadow-2xl shadow-black/50 transition-all duration-700 border border-white/10 max-sm:w-[180px] max-sm:h-[180px] max-sm:rounded-[30px]"
            style={{ backgroundImage: `url(${thumbnailUrl || bannerUrl})`, opacity: loaded ? 1 : 0 }}
          />
        )}
      </div>

      {/* Podcast name */}
      <p className="absolute top-[55%] left-1/2 -translate-x-1/2 text-2xl font-bold z-10 text-center font-[family-name:var(--font-parkinsans)] text-white max-w-[80%] transition-opacity duration-700 max-sm:text-lg max-sm:top-[52%]" style={{ opacity: loaded ? 1 : 0 }}>
        {podcastName}
      </p>
      <p className="absolute top-[63%] left-1/2 -translate-x-1/2 text-xs z-10 w-[80%] text-center text-white/40 font-[family-name:var(--font-parkinsans)] max-sm:top-[60%]">
        Generated by Elixpo Copilot. There might be mistakes
      </p>

      {/* Source */}
      {sourceLink && (
        <div className="absolute top-[68%] left-1/2 -translate-x-1/2 z-10 max-sm:top-[65%]">
          <SourcePill sourceLink={sourceLink} />
        </div>
      )}

      {/* Playback zone */}
      <div className="absolute top-[78%] left-1/2 -translate-x-1/2 w-[30%] h-[100px] rounded-[25px] z-10 select-none max-lg:w-[50%] max-sm:w-[85%] max-sm:top-[74%]" style={{ background: "rgba(255,255,255,0.08)", backdropFilter: "blur(20px)", boxShadow: "0 8px 32px rgba(0,0,0,0.3)" }}>
        {/* Seek */}
        <div className="relative flex items-center w-[90%] h-[40%] left-[5%] top-[10%] gap-5">
          <button onClick={cycleSpeed} className="font-[family-name:var(--font-parkinsans)] font-bold rounded-lg px-2 py-0.5 text-white/80 text-sm cursor-pointer">{speed}x</button>
          <div ref={seekBarRef} onClick={seekTo} className="relative w-[75%] h-[5px] rounded-[10px] cursor-pointer" style={{ background: "rgba(255,255,255,0.3)" }}>
            <div className="absolute h-[5px] rounded-[20px] top-0 left-0 bg-white" style={{ width: `${percent}%` }} />
            <div className="absolute w-3 h-3 rounded-full -top-[3.5px] z-[1] bg-white cursor-pointer" style={{ left: `${percent}%`, transform: "translateX(-50%)" }} />
          </div>
          <span className="font-[family-name:var(--font-parkinsans)] font-bold text-white/80 text-sm">{formatTime(duration - currentTime)}</span>
        </div>

        {/* Controls */}
        <div className="relative flex items-center justify-between w-[50%] h-[40%] left-1/2 -translate-x-1/2 top-[10%]">
          <svg viewBox="0 0 24 24" className="w-6 h-6 cursor-pointer" onClick={() => skip(-10)}>
            <path d="M2.74999 2.5C2.33578 2.5 2 2.83579 2 3.25V8.75C2 9.16421 2.33578 9.5 2.74999 9.5H8.25011C8.66432 9.5 9.00011 9.16421 9.00011 8.75C9.00011 8.33579 8.66432 8 8.25011 8H4.34273C5.40077 6.60212 6.77033 5.4648 8.47169 4.93832C10.5381 4.29885 12.7232 4.35354 14.7384 5.10317C16.7673 5.85787 18.6479 7.38847 19.5922 9.11081C19.7914 9.47401 20.2473 9.607 20.6104 9.40785C20.9736 9.20871 21.1066 8.75284 20.9075 8.38964C19.7655 6.30687 17.5773 4.55877 15.2614 3.69728C12.9318 2.83072 10.4069 2.7693 8.02826 3.50536C6.14955 4.08673 4.65345 5.26153 3.49999 6.64949V3.25C3.49999 2.83579 3.1642 2.5 2.74999 2.5Z" fill="white" />
          </svg>
          <svg viewBox="0 0 32 32" className="w-8 h-8 cursor-pointer" onClick={togglePlay}>
            {isPlaying ? (
              <path d="M7.25 29C5.45507 29 4 27.5449 4 25.75V7.25C4 5.45507 5.45507 4 7.25 4H10.75C12.5449 4 14 5.45507 14 7.25V25.75C14 27.5449 12.5449 29 10.75 29H7.25ZM21.25 29C19.4551 29 18 27.5449 18 25.75V7.25C18 5.45507 19.4551 4 21.25 4H24.75C26.5449 4 28 5.45507 28 7.25V25.75C28 27.5449 26.5449 29 24.75 29H21.25Z" fill="white" />
            ) : (
              <path d="M12.2246 27.5373C9.89137 28.8585 7 27.173 7 24.4917V7.50044C7 4.81864 9.89234 3.1332 12.2256 4.45537L27.2233 12.9542C29.5897 14.2951 29.5891 17.7047 27.2223 19.0449L12.2246 27.5373Z" fill="white" />
            )}
          </svg>
          <svg viewBox="0 0 24 24" className="w-6 h-6 cursor-pointer" onClick={() => skip(10)}>
            <path d="M21.25 2.5C21.6642 2.5 22 2.83579 22 3.25V8.75C22 9.16421 21.6642 9.5 21.25 9.5H15.7499C15.3357 9.5 14.9999 9.16421 14.9999 8.75C14.9999 8.33578 15.3357 8 15.7499 8H19.6573C18.5992 6.60212 17.2297 5.4648 15.5283 4.93832C13.4619 4.29885 11.2768 4.35354 9.26156 5.10317C7.23271 5.85787 5.35214 7.38846 4.40776 9.11081C4.20861 9.47401 3.75274 9.607 3.38955 9.40785C3.02635 9.20871 2.89336 8.75283 3.09251 8.38964C4.23451 6.30687 6.42268 4.55877 8.73861 3.69728C11.0682 2.83072 13.5931 2.7693 15.9717 3.50536C17.8504 4.08673 19.3465 5.26153 20.5 6.64949V3.25C20.5 2.83579 20.8358 2.5 21.25 2.5Z" fill="white" />
          </svg>
        </div>
      </div>
    </section>
  );
}
